name: ğŸš€ FTP Deploy - Al Motammem

on:
  push:
    branches: [ "snapscrollabout" ]   # Ø£ÙŠ push Ø¹Ù„Ù‰ main Ù‡ÙŠØ¹Ù…Ù„ deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

# âœ… Generate sitemap.xml (dynamic blogs)
      - name: Generate sitemaps (index + static + blogs)
        run: node scripts/generate-sitemaps.mjs

      # Ù‡Ù†Ø§ Ø¨ÙŠØ±ÙØ¹ Ø§Ù„Ù€ build Ø¹Ù„Ù‰ Ø§Ù„Ø³ÙŠØ±ÙØ± Ø¹Ù† Ø·Ø±ÙŠÙ‚ FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}        # 91.229.118.182
          username: ${{ secrets.FTP_USER }}      # MOTDEV
          password: ${{ secrets.FTP_PASS }}      # Ø§Ù„Ø¨Ø§Ø³ÙˆØ±Ø¯ Ø§Ù„Ù„ÙŠ Ø¶ÙØªÙ‡
          port: ${{ secrets.FTP_PORT }}          # 21
          local-dir: dist/al-motammem/            # ÙÙˆÙ„Ø¯Ø± Ø§Ù„Ù€ build ÙÙŠ Ø§Ù„Ø±ÙŠØ¨Ùˆ
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}  # /dist/al-motammem/
